name: Residewise

on:
    push:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   run: echo "$SECRETS"
                env:
                    SECRETS: ${{ toJson(secrets) }}
